objective:
  - reconstruction_objective

dataset:
  - radio_interferometry:
      fits_name : "RA_18.7117_DEC_0.3194_size_1024.fits"
      image_size: 1024
      noise_level: 0.1
      simulator_hash: "892471111a25f7dda75b0f4670d43bfb"

solver:
  - PnP:
      denoiser: drunet
      distribute_physics: False
      distribute_denoiser: False
      init_method: ["adjoint"]
      norm_strategy: ["dynamic"]
      slurm_gres, slurm_ntasks_per_node, distribute_physics, distribute_denoiser, patch_size, denoiser_sigma: [
        ["gpu:0", 4, true, true, [128], 0.001]
      ]
      
