objective:
  - reconstruction_objective

# Dataset
dataset:
  - tomography_3d_train:
      num_projs: [[30, 50, 100]]
      # max_train_samples : 6
      # max_val_samples : 3
      batch_size: 1


# Solver
solver:
  - UnrolledPnP:
      denoiser: drunet
      n_iter: 4
      init_stepsize: 0.9
      denoiser_sigma: 0.005
      lambda_relaxation: true
      learning_rate: 1e-4
      model_learning_rate: 1e-4
      operator_norm: 1.0
      grad_accumulation_steps: 12
      slurm_gres, slurm_ntasks_per_node, slurm_nodes,distribute_model, patch_size, overlap, max_batch_size: [
        ["gpu:4", 4, 4, true, [128, 128, 128], [16, 16, 16], 1],   
      ]   


# Run parameters
max-runs: 4
n-repetitions: 1
