# Benchopt configuration for distributed benchmarking with Urban100
# This file specifies testing with 2 distributed processes

# Objective filter
objective:
  - reconstruction_objective

# Dataset filters
dataset:
  - urban100:
      image_size: 512
      num_operators: 4
      train_images: 32
      val_images: 8
      batch_size: 1
      noise_level: 0.06


# Solver filters
solver:
  - UnrolledPnP:
      denoiser: drunet
      n_iter: 4
      init_stepsize: 0.9
      denoiser_sigma: 0.05
      learning_rate: 0.01
      slurm_gres, slurm_ntasks_per_node, slurm_nodes, distribute_physics, distribute_denoiser, patch_size, overlap, max_batch_size: [
        ["gpu:1", 1, 1, false, false, 0, 0, 0],
        ["gpu:2", 2, 1, true, true,256, 32, 1],
        #["gpu:4", 4, 1, true, true, 256, 32, 4],
      ]

# Run parameters
max-runs: 5
n-repetitions: 1
